Repository SOPT-all/36-COLLABORATION-SERVER-HOLIX, pull requests merged in 2025-05, with the labels that each got.

#4 [Setting]/#3 공통 응답 구조와 예외처리를 진행합니다
  src/main/java/com/holix/holix_server/global/code/CommonErrorCode.java
  src/main/java/com/holix/holix_server/global/code/CommonSuccessCode.java
  src/main/java/com/holix/holix_server/global/code/ErrorCode.java
  src/main/java/com/holix/holix_server/global/code/SuccessCode.java
  src/main/java/com/holix/holix_server/global/exception/BusinessException.java
  src/main/java/com/holix/holix_server/global/exception/GlobalExceptionHandler.java
  src/main/java/com/holix/holix_server/global/exception/MethodNotSupportedException.java
  src/main/java/com/holix/holix_server/global/exception/NoHandlerFoundException.java
  src/main/java/com/holix/holix_server/global/response/HolixResponse.java
  src/main/java/com/holix/holix_server/sample/code/SampleErrorCode.java
  src/main/java/com/holix/holix_server/sample/controller/SampleController.java
  src/main/java/com/holix/holix_server/sample/dto/response/SampleResponseDTO.java
  src/main/java/com/holix/holix_server/sample/service/SampleConstant.java
  src/main/java/com/holix/holix_server/sample/service/SampleService.java
Labels: 혜음⊹꒰⍢⑅ ꒱꙳, setting

#6 [Feature]/#5 도메인 구조를 구성하고, 채팅 조회 & 전송 API를 구현합니다.
  src/main/java/com/holix/holix_server/club/code/ClubErrorCode.java
  src/main/java/com/holix/holix_server/club/controller/ClubController.java
  src/main/java/com/holix/holix_server/club/dto/request/ChattingCreateRequestDTO.java
  src/main/java/com/holix/holix_server/club/dto/response/ChattingListResponseDTO.java
  src/main/java/com/holix/holix_server/club/dto/response/ChattingResponseDTO.java
  src/main/java/com/holix/holix_server/club/model/Chatting.java
  src/main/java/com/holix/holix_server/club/model/ChattingType.java
  src/main/java/com/holix/holix_server/club/model/Club.java
  src/main/java/com/holix/holix_server/club/repository/ChattingRepository.java
  src/main/java/com/holix/holix_server/club/repository/ClubRepository.java
  src/main/java/com/holix/holix_server/club/service/ClubService.java
  src/main/java/com/holix/holix_server/user/code/UserErrorCode.java
  src/main/java/com/holix/holix_server/user/model/User.java
  src/main/java/com/holix/holix_server/user/repository/UserRepository.java
Labels: 윤혁 ദ്ദി '֊' ), feature

#12 [Fix]/#10: 잘못 처리한 status 를 변경합니다 (400->404)
  src/main/java/com/holix/holix_server/global/code/CommonErrorCode.java
Labels: 혜음⊹꒰⍢⑅ ꒱꙳, fix

#9 [Feature]/#8 클럽 조회 & 상세 조회 & 핀 상태 변경 api를 구현합니다
  src/main/java/com/holix/holix_server/club/controller/ClubController.java
  src/main/java/com/holix/holix_server/club/dto/response/ClubDetailResponseDTO.java
  src/main/java/com/holix/holix_server/club/dto/response/ClubListResponseDTO.java
  src/main/java/com/holix/holix_server/club/dto/response/ClubPinResponseDTO.java
  src/main/java/com/holix/holix_server/club/dto/response/ClubResponseDTO.java
  src/main/java/com/holix/holix_server/club/extension/ClubExtension.java
  src/main/java/com/holix/holix_server/club/model/Club.java
  src/main/java/com/holix/holix_server/club/repository/ClubRepository.java
  src/main/java/com/holix/holix_server/club/service/ClubService.java
Labels: api, 혜음⊹꒰⍢⑅ ꒱꙳, feature

#18 [Fix]/#16 url 타입을 변경합니다 & extension format 을 변경합니다
  src/main/java/com/holix/holix_server/club/extension/ClubExtension.java
  src/main/java/com/holix/holix_server/club/model/Club.java
Labels: 혜음⊹꒰⍢⑅ ꒱꙳, fix

#21 [Refactor]/#20: 채팅 DTO 필드명을 변경합니다.
  src/main/java/com/holix/holix_server/club/dto/response/ChattingListResponseDTO.java
Labels: 윤혁 ദ്ദി '֊' ), feature
